# Generated by Django 3.2.9 on 2021-11-25 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211125_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectpeople',
            name='person_who_follow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('61ada6e3-e8f0-47da-ba7b-4b2104a6eda6'), unique=True),
        ),
    ]
