# Generated by Django 3.2.9 on 2021-11-25 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211125_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e6b9fb55-a56f-4d22-bebc-af862c7e5e57'), unique=True),
        ),
        migrations.AlterField(
            model_name='connectpeople',
            name='person_who_follow',
            field=models.IntegerField(default=0),
        ),
    ]
